apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer  # or ClusterIP or NodePort, depending on your use case
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
